sudo: required
services:
  - docker

before_install:
  - docker build -t michaelslatterydev/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true michaelslatterydev/react-test npm test

after_success:
  - docker build -t michaelslatterydev/multi-client ./client
  - docker build -t michaelslatterydev/multi-nginx ./nginx
  - docker build -t michaelslatterydev/multi-server ./server
  - docker build -t michaelslatterydev/multi-worker ./worker
  # Log in to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Push to docker hub
  - docker push michaelslatterydev/multi-client
  - docker push michaelslatterydev/multi-nginx
  - docker push michaelslatterydev/multi-server
  - docker push michaelslatterydev/multi-worker

deploy:
  provider: elasticbeanstalk
  region: 'eu-west-1'
  app: 'multi-docker'
  env: 'MultiDocker-env'
  bucket_name: 'elasticbeanstalk-eu-west-1-530348237546'
  bucket_path: 'docker-multi'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
